### ISSUE TITLE
Add Yagusmart Tuya 2 button to Edge Button driver

### ISSUE THREAD

**Issue by pedutton** [erickvneri/erickv-edge-drivers#5]
Hi
Is it possible to please add the following to your Edge Button Driver:

Mfg Code | _TZ3000_adkvzooy
Model | TS0042
ocf Type | x.com.st.d.remotecontroller

It is a 2 button, battery  remote controller that looks like a standard wall switch.
I think I ordered them as Yagusmart - but they come in a generic box - for working with Tuya Zigbee

I have tried your v1.4.4 driver and it is not picking them up (they are currently being picked up as powered switch by a different driver!)
Anything you can do to help would be fantastic.

Thanks
Peter

**Comment by erickvneri** [comment]
Hello, @pedutton

Thanks for reaching out. I added the fingerprint in commit [c665ec2dbec5daee1f216df66ad48527e1f29144](https://github.com/erickvneri/erickv-edge-drivers/commit/c665ec2dbec5daee1f216df66ad48527e1f29144) and it is already published on the channles.

**Comment by pedutton** [comment]
Fantastic.
Managed to switch to this driver now... really appreciate the insanely
quick help.
Peter
